# Generated by Django 6.0.3 on 2026-03-17 09:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('unit', models.CharField(default='nos', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Indent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(max_length=255)),
                ('justification', models.TextField(blank=True, default='')),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('UNDER_HOD_REVIEW', 'Under HOD Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('FORWARDED', 'Forwarded')], default='DRAFT', max_length=30)),
                ('stock_available', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pending_indents', to='accounts.extrainfo')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='indents', to='accounts.departmentinfo')),
                ('indenter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='indents', to='accounts.extrainfo')),
            ],
        ),
        migrations.CreateModel(
            name='IndentAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acting_role', models.CharField(max_length=50)),
                ('action', models.CharField(max_length=50)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('indent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='ps.indent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CurrentStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='ps.storeitem')),
            ],
        ),
        migrations.CreateModel(
            name='IndentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('indent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ps.indent')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='indent_lines', to='ps.storeitem')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('indent', 'item'), name='uniq_item_per_indent')],
            },
        ),
    ]
