# Generated by Django 6.0.3 on 2026-03-17 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='indent',
            name='procurement_type',
            field=models.CharField(blank=True, choices=[('INTERNAL', 'Internal Stock'), ('EXTERNAL', 'External Procurement')], max_length=20, null=True),
        ),
    ]
