# Generated by Django 4.2.16 on 2026-03-19 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ps', '0002_indent_procurement_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentstock',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='indent',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='indent',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('UNDER_HOD_REVIEW', 'Under HOD Review'), ('STOCK_CHECKED', 'Stock Checked'), ('INTERNAL_ISSUED', 'Internal Issued'), ('EXTERNAL_PROCUREMENT', 'External Procurement'), ('FORWARDED_TO_DIRECTOR', 'Forwarded to Director'), ('APPROVED_BY_DEP_ADMIN', 'Approved by Dept Admin'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('FORWARDED', 'Forwarded')], default='DRAFT', max_length=30),
        ),
        migrations.AlterField(
            model_name='indentaudit',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='indentitem',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='storeitem',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
