# Generated by Django 4.2.16 on 2026-03-19 18:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ps', '0003_alter_currentstock_id_alter_indent_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acting_role', models.CharField(max_length=50)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_entries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='currentstock',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='indent',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='indent',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('UNDER_HOD_REVIEW', 'Under HOD Review'), ('STOCK_CHECKED', 'Stock Checked'), ('INTERNAL_ISSUED', 'Internal Issued'), ('EXTERNAL_PROCUREMENT', 'External Procurement'), ('FORWARDED_TO_DIRECTOR', 'Forwarded to Director'), ('APPROVED_BY_DEP_ADMIN', 'Approved by Dept Admin'), ('APPROVED', 'Approved'), ('STOCKED', 'Stocked'), ('REJECTED', 'Rejected'), ('FORWARDED', 'Forwarded')], default='DRAFT', max_length=30),
        ),
        migrations.AlterField(
            model_name='indentaudit',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='indentitem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='storeitem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='StockEntryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_entry_lines', to='ps.storeitem')),
                ('stock_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ps.stockentry')),
            ],
        ),
        migrations.AddField(
            model_name='stockentry',
            name='indent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_entries', to='ps.indent'),
        ),
        migrations.AddConstraint(
            model_name='stockentryitem',
            constraint=models.UniqueConstraint(fields=('stock_entry', 'item'), name='uniq_item_per_stock_entry'),
        ),
    ]
