# Generated by Django 4.2.16 on 2026-03-25 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ps', '0004_stockentry_alter_currentstock_id_alter_indent_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indent',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('UNDER_HOD_REVIEW', 'Under HOD Review'), ('STOCK_CHECKED', 'Stock Checked'), ('INTERNAL_ISSUED', 'Internal Issued'), ('EXTERNAL_PROCUREMENT', 'External Procurement'), ('FORWARDED_TO_DIRECTOR', 'Forwarded to Director'), ('APPROVED_BY_DEP_ADMIN', 'Approved by Dept Admin'), ('APPROVED', 'Approved'), ('STOCKED', 'Stocked'), ('REJECTED', 'Rejected'), ('FORWARDED', 'Forwarded'), ('BIDDING', 'Bidding'), ('PURCHASED', 'Purchased')], default='DRAFT', max_length=30),
        ),
    ]
